YiQ/urls.py
from django.contrib import admin
from django.urls import path
from StuLogin.views import *
urlpatterns = [
    path('admin/', admin.site.urls),
    path('stulogin/', stulogin),
    path('login/',login),
    path('facility/',showFacility),
    path('facility/<str:fid>',facilityDetail),
    path('facility/<str:fid>/comment',showComment),
    path('showInfo/<str:id>',showInfo),
    path('repair/',repair),
    # path(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT})
]

StuLogin/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Comment(models.Model):
    index = models.AutoField(primary_key=True)
    fid = models.CharField(max_length=20)
    id = models.IntegerField()
    text = models.CharField(max_length=255, blank=True, null=True)
    date = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'comment'
        unique_together = (('index', 'fid', 'id'),)


class Facility(models.Model):
    index = models.AutoField(primary_key=True)
    fid = models.CharField(db_column='FID', max_length=20)  # Field name made lowercase.
    status = models.IntegerField(db_column='Status')  # Field name made lowercase.
    type = models.IntegerField(db_column='Type')  # Field name made lowercase.
    address = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = 'facility'
        unique_together = (('index', 'fid'),)


class User(models.Model):
    index = models.AutoField(primary_key=True)
    id = models.IntegerField(db_column='ID')  # Field name made lowercase.
    type = models.IntegerField(db_column='Type')  # Field name made lowercase.
    pwd = models.CharField(max_length=25)
    name = models.CharField(max_length=25)

    class Meta:
        managed = False
        db_table = 'user'
        unique_together = (('index', 'id'),)

models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Comment(models.Model):
    index = models.AutoField(primary_key=True)
    fid = models.CharField(max_length=20)
    id = models.IntegerField()
    text = models.CharField(max_length=255, blank=True, null=True)
    date = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'comment'
        unique_together = (('index', 'fid', 'id'),)


class Facility(models.Model):
    index = models.AutoField(primary_key=True)
    fid = models.CharField(db_column='FID', max_length=20)  # Field name made lowercase.
    status = models.IntegerField(db_column='Status')  # Field name made lowercase.
    type = models.IntegerField(db_column='Type')  # Field name made lowercase.
    address = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = 'facility'
        unique_together = (('index', 'fid'),)


class User(models.Model):
    index = models.AutoField(primary_key=True)
    id = models.IntegerField(db_column='ID')  # Field name made lowercase.
    type = models.IntegerField(db_column='Type')  # Field name made lowercase.
    pwd = models.CharField(max_length=25)
    name = models.CharField(max_length=25)

    class Meta:
        managed = False
        db_table = 'user'
        unique_together = (('index', 'id'),)


class WRecords(models.Model):
    index = models.AutoField(primary_key=True)
    fid = models.CharField(max_length=20)
    id = models.IntegerField()
    date = models.DateTimeField(blank=True, null=True)
    text = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'w_records'

StuLogin/views.py
from django.shortcuts import render, render_to_response

# Create your views here.

from django.template.loader import get_template
from django.contrib.auth import authenticate, login

from .models import *
from django.http import HttpResponse
from django.template import RequestContext
from django.shortcuts import redirect
from django import forms

class UserForm(forms.Form):
    username = forms.CharField(label='用户名',max_length=50)
    password = forms.CharField(label='密码',widget=forms.PasswordInput())


class RepairForm(forms.Form):
    fid = forms.CharField(label='设备ID', max_length=20)
    id = forms.CharField(label='学生ID', max_length=50)
    text = forms.CharField(label='报修内容<br>',widget=forms.Textarea)


def login(request):
    if request.method == 'POST':
        userform = UserForm(request.POST)
        if userform.is_valid():
            username = userform.cleaned_data['username']
            password = userform.cleaned_data['password']

            user = User.objects.get(id=username,pwd=password)

            if user:
                #登录成功
                #跳转到展示信息
                if(user.type== 1): #如果用户是学生的话
                    return redirect('http://127.0.0.1:8000/showInfo/'+username)
                elif(user.type==2): #如果用户是管理员的话，跳转到设备界面
                    return redirect('http://127.0.0.1:8000/facility/')
            else:
                return HttpResponse('用户名或密码错误,请重新登录')

    else:
        userform = UserForm()
    return render_to_response('login.html')

def repair(request):
    if request.method == 'POST':
        repairform = RepairForm(request.POST)
        if repairform.is_valid():
            fid = repairform.cleaned_data['fid']
            id = repairform.cleaned_data['id']
            # 对id和fid 验证
            f = Facility.objects.get(fid = fid)
            u = User.objects.get(id = id)
            if f and u:
                text = repairform.cleaned_data['text']
                repairData = WRecords.objects.create(fid=fid,id=id,text=text)
                print(type(repairData), repairData)
                return HttpResponse("报修成功")
            else:
                return HttpResponse("设备ID或学生ID不存在")
    else:
        repairform = RepairForm()
    return render_to_response('repair.html')
def showInfo(request,id):
    template = get_template('showInfo.html')
    u=User.objects.get(id=id)
    html = template.render(locals())
    return HttpResponse(html)

def showFacility(request):
    template = get_template('showFacility.html')
    f_list = Facility.objects.all()
    html = template.render(locals())
    return HttpResponse(html)
def facilityDetail(request,fid):
    t = get_template('facilityDetail.html')
    try:
        f=Facility.objects.get(fid=fid)
        if f != None:
            html = t.render(locals())
            return HttpResponse(html)
    except:
        return redirect('/')

def showComment(request,fid):
    template = get_template('showComment.html')
    c_list = Comment.objects.filter(fid=fid)
    html = template.render(locals())
    return HttpResponse(html)




def stulogin(request):
    return redirect("http://www.baidu.com")

templates/facilityDetail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ fid }}管理页面</title>
    <link rel="stylesheet" href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
<table class="table table-bordered">

    <thead>
    <tr>
        <th>基本信息</th>
        <th>数据</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>设备类型</td>
        <td> {% if f.type == 1 %}
            空调
        {% elif f.type == 2 %}
            电梯
        {% else %}
            新设备
        {% endif %}</td>

    </tr>
    <tr>
        <td>设备编号</td>
        <td>{{ f.fid }}</td>
    </tr>
    <tr>
        <td>设备地址</td>
        <td>{{ f.address }}</td>
    </tr>
    <tr>
        <td>设备状况</td>
        <td>
            {% if f.status == 1 %}
                正在工作
            {% elif f.status == 0 %}
                正在维修
            {% else %}
                特殊情况，原因不明
            {% endif %}
        </td>
    </tr>
    </tbody>
</table>


<h3>
    <a href="/facility/{{ f.fid }}/comment">点击查看 {{ f.fid }} 的评论</a>
    <a href="/">回首页</a>
</h3>
</body>
</html>

templates/login.html
<!DOCTYPE html>

<html lang="zh-CN">
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Login</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="/static/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/static/css/signin.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="/static/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link rel="stylesheet" href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="../static/style/login.css" type="text/css">
</head>
<style>
    html, body {
        text-align: center;
        margin: 0px auto;
    }
</style>
<body>
<h1>登录页面</h1>


<div style="padding: 100px 100px 10px;">
    <form class="bs-example bs-example-form" role="form" method='post' enctype="multipart/form-data">
        <div class="input-group">
            <span class="input-group-addon">用户名</span>
            <input type="text" class="form-control" name="username" id="id_username"
                   maxlength="50" required>
        </div>
        <br>
        <div class="input-group">
            <span class="input-group-addon">密&nbsp;&nbsp;&nbsp;&nbsp;码</span>
            <input class="form-control" type="password" name="password"
                   id="id_password" required>
        </div>
        <input class="btn btn-lg btn-success" type="submit" value="Login">
        <input class="btn btn-lg btn-warning" type="reset" value="Reset">
    </form>
</div>


</body>
</html>

templates/repair.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>报修页面</title>
    <link rel="stylesheet" href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>


<form class="form-horizontal" role="form" method='post' enctype="multipart/form-data">
    <div class="col-sm-offset-3 col-sm-9"><h1>报修页面</h1></div>
    <div class="form-group">
        <label for="firstname" class="col-sm-2 control-label">设备ID:</label>
        <div class="col-sm-6">
            <input type="text" class="form-control" name="fid" required id="id_fid" maxlength="20">
        </div>
    </div>
    <div class="form-group">
        <label for="firstname" class="col-sm-2 control-label">学生ID:</label>
        <div class="col-sm-6">
            <input type="text" class="form-control" name="id" required id="id_id" maxlength="50">
        </div>
    </div>

    <div class="form-group">
        <label for="firstname" class="col-sm-2 control-label">报修内容</label>
        <div class="col-sm-6">
            <textarea class="form-control " name="text" required rows="10" id="id_text"></textarea>
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">点击报修</button>
        </div>
    </div>
</form>
</body>
</html>

templates/showComment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>设备评论区</title>
    <link rel="stylesheet" href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">设备评论区</a>
        </div>
    </div>
</nav>
<table class="table table-bordered">
    <tbody>


    {% for comment  in c_list %}
        <tr>
            <p>

                内容：
            <pre>{{ comment.text }}</pre>
            </p>
            <p>
                发布时间：{{ comment.date }}
            </p>
            <p>
                发布者：{{ comment.id }}
                <a href="comment/{{ comment.index }}">管理评论</a>
            </p>
        </tr>

    {% endfor %}
    </tbody>
</table>
</body>
</html>

templates/showFacility.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>设备列表</title>
    <link rel="stylesheet" href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">易勤平台</a>
        </div>
    </div>
</nav>
<table class="table table-striped">
    <thead>
    <tr>
        <th>设备编号</th>
        <th>设备类型</th>
        <th>所在地点</th>
    </tr>
    </thead>
    <tbody>


    {% for facility in f_list %}
        <tr>
            <td><a href="/facility/{{ facility.fid }}">{{ facility.fid }}</a></td>

            <td>
                {% if facility.type == 1 %}
                    空调
                {% elif facility.type == 2 %}
                    电梯
                {% else %}
                    新设备
                    </td>
                {% endif %}
            <td>
                {{ facility.address }}
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>
</body>
</html>

templates/showInfo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>个人信息</title>
    <link rel="stylesheet" href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">易勤平台</a>
        </div>
        <ul class="nav navbar-nav navbar-right">
            <li><a href="#"><span class="glyphicon glyphicon-user" style="font-size: 20px"></span> {{ u.name }}</a></li>
            <li>
                {% if u.type == 1 %}
                    <a href="http://127.0.0.1:8000/repair/"><span class="glyphicon glyphicon-zoom-in"
                                                                  style="font-size: 20px"></span> 点击报修</a>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>
</body>
</html>